title: My CV Website
description: A simple CV creation page.
theme: jekyll-theme-merlot

# Optional settings
url: "https://peace5000.github.io/career.craft/"  # Replace with your GitHub Pages URL
author: "Peace Khutso The software Tech Guru"

