title: My CV Website
description: A simple CV creation page.
theme: jekyll-theme-merlot

# Optional settings
url: "https://yourusername.github.io/career.craft"  # Replace with your GitHub Pages URL
author: "Your Name"

